<?php

namespace DarkGhostHunter\Fluid;

use DarkGhostHunter\Fluid\Exceptions\InvalidAttributeException;

class FluidFillable extends Fluid
{
    /**
     * Attributes that can be filled
     *
     * @var array
     */
    protected $fillable;

    /**
     * Set the fillable attributes
     *
     * @param array $attributes
     * @throws InvalidAttributeException
     */
    public function setAttributes(array $attributes)
    {
        foreach ($attributes as $key => $attribute) {
            if (!in_array($key, $this->fillable)) {
                throw new InvalidAttributeException($key);
            }
        }

        parent::setAttributes($attributes); // TODO: Change the autogenerated stub
    }

    /**
     * Sets a fillable attribute
     *
     * @param string $key
     * @param $value
     * @return void
     * @throws InvalidAttributeException
     */
    public function setAttribute(string $key, $value)
    {
        if (!in_array($key, $this->fillable)) {
            throw new InvalidAttributeException($key);
        }

        return parent::setAttribute($key, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Get the fillable attributes
     *
     * @return array
     */
    public function getFillable()
    {
        return $this->fillable;
    }

    /**
     * Set the fillable attributes
     *
     * @param array $fillable
     */
    public function setFillable(array $fillable)
    {
        $this->fillable = $fillable;
    }


}